name: Backend CI

on:
  pull_request:
    branches: [ main, develop, feature/**, release/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Setup variables
      env: 
        DATABASE_URL: postgresql://root:test@localhost:5432/snapcode
        DB_PASSWORD: test
    - name: Install dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm run docker:up
    - run: npm test
    - run: npm run docker:down