name: Backend CI

on:
  pull_request:
    branches: [ main, develop, feature/**, release/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Docker
        run: docker-compose up -d

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm docker:down